apiVersion: apps/v1
kind: Deployment
metadata:
  name: chwcom
  labels:
    app: chwcom
spec:
  selector:
    matchLabels:
      app: chwcom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chwcom
    spec:
      containers:
      - image: jkozik/chw.com:v1.9
        name: chwcom
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            ephemeral-storage: 10M
            memory: 100M
          limits:
            ephemeral-storage: 20M
            memory: 200M          
        ports:
        - containerPort: 80
          name: chwcom
        volumeMounts:
        - name: chwcom-persistent-storage
          mountPath: "/var/www/html/mount" 
      volumes:
      - name: chwcom-persistent-storage
        persistentVolumeClaim:
          claimName: chwcom-persistent-storage
