apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chwcom-persistent-storage
  labels:
    app: chwcom
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-weather      #nfs
